//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class news
    {
        public int ID { get; set; }
        public string title { get; set; }
        public string image { get; set; }
        public string link { get; set; }
        public string summary { get; set; }
        public string cat { get; set; }
        public string tag { get; set; }
        public Nullable<System.DateTime> publishDate { get; set; }
        public int userID { get; set; }
        public string Content { get; set; }
        public Nullable<int> views { get; set; }
    }
}
