//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class response
    {
        public int ID { get; set; }
        public string title { get; set; }
        public string content { get; set; }
        public Nullable<int> adminid { get; set; }
        public Nullable<int> ticketid { get; set; }
    }
}
