//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class viewlog
    {
        public int ID { get; set; }
        public string ipadd { get; set; }
        public Nullable<int> newsid { get; set; }
        public Nullable<System.DateTime> viewdate { get; set; }
    }
}
